name: CI Tests (Jest & Playwright)


on:
  push:
    branches: [ main, "lab-*" ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: sehub_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: "postgresql://postgres:password@localhost:5432/sehub_test?schema=public"
      NEXTAUTH_SECRET: "super-secret-ci-key"
      NEXTAUTH_URL: "http://localhost:3000"

    steps:
      - name: Отримання коду репозиторію
        uses: actions/checkout@v4

      - name: Налаштування Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Встановлення залежностей
        run: npm install

      - name: Генерація клієнта Prisma
        run: npx prisma generate

      - name: Синхронізація структури БД
        run: npx prisma db push

      - name: Запуск Unit-тестів (Jest)
        run: npm run test

      - name: Встановлення браузерів для Playwright
        run: npx playwright install --with-deps

      - name: Запуск E2E-тестів (Playwright)
        run: npx playwright test
